# Environment variables are defined in default.env file
version: "3"
services:

  kn-hw-be:
    build:
      context: ./back
    ports:
      - "9090:8666"

  kn-hw-fe:
    build:
      context: ./front
      args:
        API_ENDPOINT_ARG: http://localhost:9090/kn
    ports:
      - "8080:8080"