# Environment variables are defined in default.env file
version: "3"
services:

  kn-hw-be:
    image: kn-hw-be
    env_file: default.env
    ports:
      - "9090"

  kn-hw-fe:
    image: kn-hw-fe
    env_file: default.env
    ports:
      - "8080"